similarity_dict = {
    'Idade': {
        ('Crianca',     'Crianca'):     1.0,
        ('Adolescente', 'Adolescente'): 1.0,
        ('Adulto',      'Adulto'):      1.0,
        ('Idoso',       'Idoso'):       1.0,
        ('Crianca',     'Adolescente'): 0.7,
        ('Adolescente', 'Crianca'):     0.7,
        ('Adolescente', 'Adulto'):      0.5,
        ('Adulto',      'Adolescente'): 0.5,
        ('Adulto',      'Idoso'):       0.5,
        ('Idoso',       'Adulto'):      0.5,
        ('Crianca',     'Adulto'):      0.2,
        ('Adulto',      'Crianca'):     0.2,
        ('Crianca',     'Idoso'):       0.0,
        ('Idoso',       'Crianca'):     0.0,
        ('Adolescente', 'Idoso'):       0.2,
        ('Idoso',       'Adolescente'): 0.2,
    },
    'Problema_Fisico': {
        ('Nenhum',       'Nenhum'):      1.0,
        ('Mental',       'Mental'):      1.0,
        ('Respiratorio', 'Respiratorio'): 1.0,
        ('Mobilidade',   'Mobilidade'):  1.0,
        ('Nenhum',       'Mental'):      0.5,
        ('Mental',       'Nenhum'):      0.5,
        ('Nenhum',       'Respiratorio'): 0.5,
        ('Respiratorio', 'Nenhum'):      0.5,
        ('Nenhum',       'Mobilidade'):  0.5,
        ('Mobilidade',   'Nenhum'):      0.5,
        ('Mental',       'Respiratorio'): 0.2,
        ('Respiratorio', 'Mental'):      0.2,
        ('Mental',       'Mobilidade'):  0.2,
        ('Mobilidade',   'Mental'):      0.2,
        ('Respiratorio', 'Mobilidade'):  0.2,
        ('Mobilidade',   'Respiratorio'): 0.2,
    },
    'Preferencia': {
        ('Individual', 'Individual'): 1.0,
        ('Coletivo',   'Coletivo'):   1.0,
        ('Individual', 'Coletivo'):   0.0,
        ('Coletivo',   'Individual'): 0.0,
    },
    'Local': {
        ('Aberto',      'Aberto'):      1.0,
        ('Fechado',     'Fechado'):     1.0,
        ('Indiferente', 'Indiferente'): 1.0,
        ('Aberto',      'Indiferente'): 0.8,
        ('Indiferente', 'Aberto'):      0.8,
        ('Fechado',     'Indiferente'): 0.8,
        ('Indiferente', 'Fechado'):     0.8,
        ('Aberto',      'Fechado'):     0.0,
        ('Fechado',     'Aberto'):      0.0,
    },
    'Disponibilidade': {
        ('1x', '1x'): 1.0,
        ('2x', '2x'): 1.0,
        ('3x', '3x'): 1.0,
        ('4x', '4x'): 1.0,
        ('5x', '5x'): 1.0,
        ('1x', '2x'): 0.8,
        ('2x', '1x'): 0.8,
        ('2x', '3x'): 0.8,
        ('3x', '2x'): 0.8,
        ('3x', '4x'): 0.8,
        ('4x', '3x'): 0.8,
        ('4x', '5x'): 0.8,
        ('5x', '4x'): 0.8,
        ('1x', '3x'): 0.5,
        ('3x', '1x'): 0.5,
        ('2x', '4x'): 0.5,
        ('4x', '2x'): 0.5,
        ('3x', '5x'): 0.5,
        ('5x', '3x'): 0.5,
        ('1x', '4x'): 0.2,
        ('4x', '1x'): 0.2,
        ('2x', '5x'): 0.2,
        ('5x', '2x'): 0.2,
        ('1x', '5x'): 0.0,
        ('5x', '1x'): 0.0,
    },
    'Objetivo': {
        ('Saude',      'Saude'):      1.0,
        ('Competicao', 'Competicao'): 1.0,
        ('Lazer',      'Lazer'):      1.0,
        ('Saude',      'Lazer'):      0.5,
        ('Lazer',      'Saude'):      0.5,
        ('Saude',      'Competicao'): 0.2,
        ('Competicao', 'Saude'):      0.2,
        ('Lazer',      'Competicao'): 0.3,
        ('Competicao', 'Lazer'):      0.3,
    },
    'Orcamento': {
        ('Baixo',  'Baixo'):  1.0,
        ('Medio',  'Medio'):  1.0,
        ('Alto',   'Alto'):   1.0,
        ('Baixo',  'Medio'):  0.5,
        ('Medio',  'Baixo'):  0.5,
        ('Medio',  'Alto'):   0.5,
        ('Alto',   'Medio'):  0.5,
        ('Baixo',  'Alto'):   0.0,
        ('Alto',   'Baixo'):  0.0,
    }
}
